name: Default

on:
  pull_request:
  push:


jobs:
  build:
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 11, 15, 16, 17 ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.node }}

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble --configuration-cache

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble --configuration-cache
